version: '2'

services:
  dev-linux:
    container_name: dev-linux
    hostname: dev-linux
    build:
      context: ./dev-linux
      dockerfile: Dockerfile
    image: 'dev-linux'
    # 256*1024*1024 = 268435456 Byte = 256 MB
    mem_limit: 268435456
    networks:
      - dev
      # dev:
      #   ipv4_address: 172.16.238.11
    volumes:
      - '../:/root/src'

  cypress:
    container_name: cypress
    hostname: cypress
    build:
      context: ./cypress
      dockerfile: Dockerfile
    image: 'dev-cypress'
    image: 'dev-linux'
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    networks:
      - dev
      # dev:
      #   ipv4_address: 172.16.238.12
    volumes:
      - '../tests:/root/src/cypress'

  viron:
    container_name: viron
    hostname: viron
    build:
      context: ./viron
      dockerfile: Dockerfile
    image: 'viron'
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    working_dir: /viron
    ports:
      - 8210:8080
    environment:
      - SHELL=/bin/bash
    networks:
      - dev
      # dev:
      #   ipv4_address: 172.16.238.13
    volumes:
      - ./viron/.editorconfig:/viron/.editorconfig
      - ./viron/.eslintrc.js:/viron/.eslintrc.js
      - ./viron/.stylefmtrc:/viron/.stylefmtrc
      - ./viron/.stylelintrc:/viron/.stylelintrc
      - ./viron/package-lock.json:/viron/package-lock.json
      - ./viron/package.json:/viron/package.json
      - ./viron/postcss.config.js:/viron/postcss.config.js
      - ./viron/public:/viron/public
      - ./viron/rollup.base.config.js:/viron/rollup.base.config.js
      - ./viron/rollup.config.js:/viron/rollup.config.js
      - ./viron/rollup.local.config.js:/viron/rollup.local.config.js
      - ./viron/src:/viron/src
      - ./viron/task:/viron/task
      - ./viron/test:/viron/test
    command: npm run start

  jenkins:
    container_name: jenkins
    hostname: jenkins
    image: jenkins:alpine
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    ports:
      - 8220:8080
    networks:
      - dev
      # dev:
      #   ipv4_address: 172.16.238.14

  java:
    container_name: java
    hostname: java
    build:
      context: ./java
      dockerfile: Dockerfile
      args:
        java_version: 9
    image: java
    # 1024*1024*1024 = 1073741824 Byte = 1024 MB
    mem_limit: 1073741824
    ports:
      - 8300:8300
      - 8230:8080
      - 9000:9000
    networks:
      - dev
      # dev:
      #   ipv4_address: 172.16.238.15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../spring-boot-api/:/application/
      - excluded_build:/application/build
      - excluded_gradle:/application/.gradle

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      # config:
      # - subnet: 172.16.238.0/24

volumes:
  excluded_build:
  excluded_gradle: